[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
genalgo = {path="../backend/genalgo"}
nnet = {path="../backend/nnet"}
raylib = "3.7.0" 
